apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpngs6qwp-python
  janus-idp.io/tekton: hpngs6qwp-python
  backstage.io/kubernetes-id: hpngs6qwp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hpngs6qwp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
